apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-blog
  namespace: default
spec:
  scaleTargetRef:
    name: blog-deploy
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 6
  triggers:
    - type: cron
      metadata:
        timezone: "Asia/Seoul"
        start: "00 09 * * *"
        end: "00 18 * * *"
        desiredReplicas: "3"
    - type: cpu
      metadata:
        tpye: Utilization
        value: "60"
